### ISSUE TITLE
Command failed: npm install cgb-scripts --save --save-exact --silent

### ISSUE THREAD

**Issue by casperleerink** [ahmadawais/create-guten-block#297]
### Expected Behaviour

cd into wp-content/plugins

then run

`npx create-guten-block my-project`

It should install everything normally.

### Actual Behaviour

During the installation I get the following error:

```
Command failed: npm install cgb-scripts --save --save-exact --silent
at makeError (/Users/casperleerink/.config/yarn/global/node_modules/execa/index.js:169:9)
    at /Users/casperleerink/.config/yarn/global/node_modules/execa/index.js:274:16
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async /Users/casperleerink/.config/yarn/global/node_modules/create-guten-block/app/npmInstallScripts.js:48:3 {
  code: 1,
  stdout: '',
  stderr: '',
  failed: true,
  signal: null,
  cmd: 'npm install cgb-scripts --save --save-exact --silent',
  timedOut: false,
  killed: false
}
```

I am running this on MacOS big sur 11.4, just normal intel chip. I am running my wordpress locally on a docker container. 
Tried it both with `npx create-guten-block` and `yarn create guten-block` but getting the same error.

For reference here is my `docker-compose.yaml`

```
version: "3"

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes: ["./:/var/www/html"]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:

```
